FPT_Final/Models/Entities/Trainee.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPT_Final.Models.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Trainee
    {
        public Trainee()
        {
            Images = "~/Content/Images/add.png";
        }




        public int ID { get; set; }
        [Display(Name = "Image")]
        public string Images { get; set; }
        [Display(Name = "Name of trainee")]
        public string Name { get; set; }
        public int Age { get; set; }
        public string Gender { get; set; }
        [Display(Name = "Phone Number")]
        public long PhoneNumber { get; set; }
        public string Address { get; set; }
        [Display(Name = "Programming Language")]
        public string ProgrammingLanguage { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string NewPassword { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Class> Classes { get; set; }
        [NotMapped]
        public HttpPostedFileBase ImageUpload { get; set; }
    }
}

FPT_Final/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FPT_Final.Models.Entities;

namespace FPT_Final.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }

    }
}

FPT_Final/Controllers/TraineeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using FPT_Final.Models.Entities;


namespace FPT_Final.Controllers
{
    public class TraineeController : Controller
    {
        FPTUniversityEntities2 context = new FPTUniversityEntities2();
        // GET: Trainee
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult login(Trainee model)
        {
            var result = context.Trainees.Where(x => x.Email == model.Email && x.Password == model.Password).Count();
            if (result > 0)
            {
                Session["id"] = model.ID;
                Session["email"] = model.Email;
                Session["password"] = model.Password;
               
                return View("Index");
            }
            else
            {
                ViewBag.error = "Something wrong!";
                return View("login");
            }
        }

        [HttpPost]
        public ActionResult Logout()
        {
            System.Web.Security.FormsAuthentication.SignOut();
            return RedirectToAction("login");
        }

        public ActionResult ViewProfile( )
        {
            string email = Session["email"].ToString();            
            var list = context.Trainees.Where(x => x.Email.Contains(email)).FirstOrDefault();
            return View(list);
        }
       

        public ActionResult ViewCourse(Course model)
        {
            List<Course> list = context.Courses.ToList();
            return View(list);
        }

        public ActionResult SettingAccount()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SettingAccount(Trainee model)
        {
            string email = Session["email"].ToString();
            string password = Session["password"].ToString();
            var result = context.Trainees.Where(x => x.Password == password).FirstOrDefault();
            if (result != null)
            {
                var detail = context.Trainees.FirstOrDefault(x => x.Email == email);
                if (detail != null)
                {
                    detail.Password = model.NewPassword;
                    context.SaveChanges();
                    ViewBag.Message = "change successfully!";
                }
            }
            return View();
        }
    }
}

FPT_Final/Views/Trainee/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Trainee/TraineeLayout.cshtml";
}

<h1 style="color:red">Hello My Friend</h1>
<h3>Well come to FPT training system!</h3>
<img src="https://daihoc.fpt.edu.vn/media/2019/04/173272355-w600-2829-1554360715.png" alt="Alternate Text" />

FPT_Final/Views/Trainee/Login.cshtml
@model FPT_Final.Models.Entities.Trainee
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link href="~/Content/css/styles.css" rel="stylesheet" />
    <script src="~/Scripts/js/datatables-simple-demo.js"></script>
    <script src="~/Scripts/js/scripts.js"></script>
</head>
<body>
    <div>
        <div id="layoutAuthentication_content">
            <main>
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-5">
                            <div class="card shadow-lg border-0 rounded-lg mt-5">
                                <div class="card-header"><h3 class="text-center font-weight-light my-4">Trainee Login </h3></div>
                                <div class="card-body">
                                    @ViewBag.error
                                    @using (Html.BeginForm("login", "Trainee", FormMethod.Post))
                                    {
                                        <form>
                                            <div class="form-floating mb-3">
                                                <div>
                                                    @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                                                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                                                    @Html.ValidationMessageFor(model => model.Email)
                                                </div>

                                            </div>
                                            <div class="form-floating mb-3">
                                                <div>
                                                    @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                                                    @Html.PasswordFor(model => model.Password, new { @class = "form-control" })
                                                    @Html.ValidationMessageFor(model => model.Password)
                                                </div>
                                            </div>
                                            <div class="form-check mb-3">
                                                <input class="form-check-input" id="inputRememberPassword" type="checkbox" value="" />
                                                <label class="form-check-label" for="inputRememberPassword">Remember Password</label>
                                            </div>
                                            <div class="d-flex align-items-center justify-content-between mt-4 mb-0">
                                                <a class="small" href="password.html">Forgot Password?</a>
                                                <input type="submit" name="name" value="Login" class="btn btn-primary" />
                                            </div>
                                        </form>
                                    }

                                </div>
                                <div class="card-footer text-center py-3">
                                    <div class="small"><a href="register.html">Need an account? Sign up!</a></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    </div>
</body>
</html>

FPT_Final/Views/Trainee/SettingAccount.cshtml
@model FPT_Final.Models.Entities.Trainee
@{
    ViewBag.Title = "SettingAccount";
    Layout = "~/Views/Trainee/TraineeLayout.cshtml";
}

<h2>SettingAccount</h2>
@using (Html.BeginForm("SettingAccount", "Trainee", FormMethod.Post))
{

    <table class="center">


        <tr>
            <td>Old Password</td>
            <td>
                @Html.EditorFor(pass => pass.Password)
            </td>
            <td>@Html.ValidationMessageFor(pass => pass.Password)</td>
        </tr>
        <tr class="rowspace">
            <td>New Password</td>

            <td>
                @Html.EditorFor(pass => pass.NewPassword)
            </td>
            <td>@Html.ValidationMessageFor(pass => pass.NewPassword)</td>
        </tr>

        <tr class="rowspace">
            <td colspan="3" id="button">
                <input type="submit" value="Change Password" />
            </td>
        </tr>
        <tr class="rowspace"><td colspan="3">@ViewBag.Message</td></tr>
    </table>

}

FPT_Final/Views/Trainee/ViewCourse.cshtml
@model IEnumerable<FPT_Final.Models.Entities.Course>

@{
    ViewBag.Title = "ViewCourse";
    Layout = "~/Views/Trainee/TraineeLayout.cshtml";
}

<h2>ViewCourse</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name_Course)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Time)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name_Course)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Time)
        </td>
    </tr>
}

</table>

FPT_Final/Views/Trainee/ViewProfile.cshtml
@model FPT_Final.Models.Entities.Trainee

@{
    ViewBag.Title = "ViewProfile";
    Layout = "~/Views/Trainee/TraineeLayout.cshtml";
}

<h2>My Profile</h2>

<div>
    <table>
        <tr>
            <td style="padding-top:20px">
                <strong>
                    @Html.DisplayNameFor(model => model.Images)
                </strong>
            </td>
            <td style="padding-top:20px"><img src="@Url.Content(Model.Images)" style="height:100px; width:100px;" /></td>
        </tr>
        <tr style="padding-top:20px">
            <td style="padding-top:20px">
                <strong>
                    @Html.DisplayNameFor(model => model.Name)
                </strong>
            </td>
            <td style="padding-top:20px">@Html.DisplayFor(model => model.Name)</td>
        </tr>
        <tr style="padding-top:20px">
            <td style="padding-top:20px">
                <strong>
                    @Html.DisplayNameFor(model => model.Age)
                </strong>
            </td>
            <td style="padding-top:20px">@Html.DisplayFor(model => model.Age)</td>
        </tr>
        <tr style="padding-top:20px">
            <td style="padding-top:20px">
                <strong>
                    @Html.DisplayNameFor(model => model.Gender)
                </strong>
            </td>
            <td style="padding-top:20px">@Html.DisplayFor(model => model.Gender)</td>
        </tr>
        <tr style="padding-top:20px">
            <td style="padding-top:20px">
                <strong>
                    @Html.DisplayNameFor(model => model.PhoneNumber)
                </strong>
            </td>
            <td style="padding-top:20px">@Html.DisplayFor(model => model.PhoneNumber)</td>
        </tr>
        <tr style="padding-top:20px">
            <td style="padding-top:20px">
                <strong>
                    @Html.DisplayNameFor(model => model.Address)
                </strong>
            </td>
            <td style="padding-top:20px">@Html.DisplayFor(model => model.Address)</td>
        </tr>
        <tr style="padding-top:20px">
            <td style="padding-right:20px; padding-top:20px">
                <strong>
                    @Html.DisplayNameFor(model => model.ProgrammingLanguage)
                </strong>
            </td>

            <td style="padding-top:20px">@Html.DisplayFor(model => model.ProgrammingLanguage)</td>
        </tr>
        <tr style="padding-top:20px">
            <td style="padding-top:20px">
                <strong>
                    @Html.DisplayNameFor(model => model.Email)
                </strong>
            </td>
            <td style="padding-top:20px">@Html.DisplayFor(model => model.Email)</td>
        </tr>
    </table>
</div>